/* ============================================================
   BUSCADOR DE PERFUMES PRO — data.js
   Base de datos de 50 fragancias reales (Diseñador / Árabe / Lujo)
   Fuente: top50-perfumes-referencia.md (notas y familias verificadas)
   ============================================================ */

// Rangos de precio real aproximados en USD (precio de venta habitual,
// botella estándar 90-100ml). Se usan para filtrar por presupuesto
// Y para mostrar el precio en la tarjeta de resultado.
const RANGOS_PRECIO = {
  Económico: { min: 20, max: 45, etiqueta: "$20 – $45" },
  Medio: { min: 55, max: 110, etiqueta: "$55 – $110" },
  "Sin límite": { min: 130, max: 350, etiqueta: "$130 – $350+" }
};

const PERFUMES = [
  // ================= DISEÑADOR (18) =================
  {
    id: 1,
    activo: true,
    nombre: "Dior Sauvage EDT",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 78,
    notas: "Bergamota de Calabria, pimienta / Lavanda, pachulí, vetiver / Ambroxan, cedro",
    imagen: "Dior%20Sauvage%20EDT.avif"
  },
  {
    id: 2,
    activo: true,
    nombre: "Dior Sauvage EDP",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 92,
    notas: "Bergamota, pimienta rosa / Pimienta de Sichuan, lavanda, anís estrellado / Ambroxan, vainilla",
    imagen: "Dior%20Sauvage%20EDP.avif"
  },
  {
    id: 3,
    activo: true,
    nombre: "Dior Sauvage Elixir",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 145,
    notas: "Nuez moscada, canela, cardamomo / Lavanda, coumarina / Regaliz, sándalo, ámbar, pachulí",
    imagen: "Dior%20Sauvage%20Elixir.avif"
  },
  {
    id: 4,
    activo: true,
    nombre: "Chanel Bleu de Chanel EDP",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 105,
    notas: "Cítricos, menta / Jengibre, nuez moscada / Sándalo, incienso, cedro, labdanum",
    imagen: "Chanel%20Bleu%20de%20Chanel%20EDP.avif"
  },
  {
    id: 5,
    activo: true,
    nombre: "Versace Eros",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Fiesta",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    precioUSD: 68,
    notas: "Menta, manzana verde, limón / Tonka, geranio, ambroxan / Vainilla, cedro, vetiver",
    imagen: "Versace%20Eros.avif"
  },
  {
    id: 6,
    activo: true,
    nombre: "Giorgio Armani Acqua di Giò",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 82,
    notas: "Notas marinas, bergamota, neroli / Jazmín, romero / Almizcle blanco, cedro, oakmoss",
    imagen: "Giorgio%20Acqua%20di%20Gio.avif"
  },
  {
    id: 7,
    activo: true,
    nombre: "Yves Saint Laurent Y EDP",
    tipo: "Diseñador",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 96,
    notas: "Manzana, bergamota, jengibre / Salvia, geranio, cedro / Ámbar madera, haba tonka",
    imagen: "Yves%20Saint%20Laurent%20Y%20EDP.avif"
  },
  {
    id: 8,
    activo: true,
    nombre: "Jean Paul Gaultier Le Male Elixir",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    precioUSD: 89,
    notas: "Lavanda, menta / Vainilla, benzoína / Miel, tabaco, haba tonka",
    imagen: "Le%20Male%20Elixir%20Jean%20Paul%20Gaultier%20for%20men.avif"
  },
  {
    id: 9,
    activo: true,
    nombre: "Paco Rabanne Invictus",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    momento: "Deporte",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 72,
    notas: "Toronja, mandarina marina / Laurel, jazmín / Ámbar, guaiac wood, pachulí",
    imagen: "Paco%20Rabanne%20Invictus.avif"
  },
  {
    id: 10,
    activo: true,
    nombre: "Carolina Herrera CH Men Prive",
    tipo: "Diseñador",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 65,
    notas: "Whiskey, toronja, pomelo / Cardamomo, lavanda, salvia, tomillo rojo / Cuero, haba tonka, benzoína, madera",
    imagen: "Carolina%20Herrera%20CH%20Men%20Prive.avif"
  },
  {
    id: 11,
    activo: true,
    nombre: "Prada Candy",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    momento: "Citas",
    clima: "Templado",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 88,
    notas: "Caramelo / Almizcle blanco, benzoína / Haba tonka, vainilla",
    imagen: "Prada-Candy.avif"
  },
  {
    id: 12,
    activo: true,
    nombre: "Marc Jacobs Daisy",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Diario",
    clima: "Templado",
    estilo: "Joven",
    potencia: "Suave",
    presupuesto: "Medio",
    precioUSD: 75,
    notas: "Pomelo sangre, hoja de violeta, fresa / Violeta, jazmín, gardenia / Almizcle blanco, vainilla dulce",
    imagen: "Marc%20Jacobs%20Daisy.avif"
  },
  {
    id: 13,
    activo: true,
    nombre: "Lancôme La Vie Est Belle",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 98,
    notas: "Grosella negra, pera / Iris, jazmín, azahar / Praliné, vainilla, pachulí",
    imagen: "Lanc%C3%B4me%20La%20Vie%20Est%20Belle.avif"
  },
  {
    id: 14,
    activo: true,
    nombre: "Yves Saint Laurent Opium",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    precioUSD: 85,
    notas: "Mandarina, ciruela, pimienta / Clavo, canela, jazmín / Pachulí, ámbar, vainilla, incienso",
    imagen: "Opium%20Eau%20de%20Parfum%202009%20Yves%20Saint%20Laurent%20for%20women.avif"
  },
  {
    id: 15,
    activo: true,
    nombre: "Davidoff Cool Water",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    momento: "Deporte",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Suave",
    presupuesto: "Económico",
    precioUSD: 38,
    notas: "Lavanda, menta, romero / Jazmín, geranio, sándalo / Almizcle, tabaco, ámbar",
    imagen: "Davidoff%20Cool%20Water.avif"
  },
  {
    id: 16,
    activo: true,
    nombre: "Hugo Boss Bottled",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Económico",
    precioUSD: 42,
    notas: "Manzana, ciruela, bergamota / Canela, geranio, clavo / Sándalo, cedro, vainilla",
    imagen: "Boss%20Bottled%20Hugo%20Boss%20for%20men.avif"
  },
  {
    id: 17,
    activo: true,
    nombre: "Ralph Lauren Polo Blue",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Suave",
    presupuesto: "Medio",
    precioUSD: 62,
    notas: "Melón, cítricos / Geranio, notas acuáticas / Almizcle, cedro",
    imagen: "Ralph%20Lauren%20Polo%20Blue.avif"
  },
  {
    id: 18,
    activo: true,
    nombre: "Calvin Klein CK One",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Suave",
    presupuesto: "Económico",
    precioUSD: 32,
    notas: "Bergamota, cardamomo, piña / Notas florales, nuez moscada / Almizcle, ámbar",
    imagen: "Calvin%20klein%20One%20Essence.avif"
  },

  // ================= ÁRABE (18) =================
  {
    id: 19,
    activo: true,
    nombre: "Lattafa Khamrah",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 32,
    notas: "Canela, dátiles / Vainilla, praliné / Ámbar, especias, oud",
    imagen: "Khamrah%20Lattafa%20Perfumes%20for%20women%20and%20men.avif"
  },
  {
    id: 20,
    activo: true,
    nombre: "Lattafa Yara",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    precioUSD: 26,
    notas: "Fruta de la pasión, pera, mandarina / Orquídea, jazmín, gardenia / Almizcle, vainilla, sándalo",
    imagen: "Lattafa%20Yara.avif"
  },
  {
    id: 21,
    activo: true,
    nombre: "Lattafa Asad",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 29,
    notas: "Pimienta negra, tabaco, piña / Patchouli, café, iris / Vainilla, ámbar, madera seca, benzoína, labdanum",
    imagen: "Lattafa%20Asad.avif"
  },
  {
    id: 22,
    activo: true,
    nombre: "Lattafa Bade'e Al Oud \"Oud For Glory\"",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 34,
    notas: "Azafrán, nuez moscada, lavanda / Agarwood (oud), patchouli / Agarwood (oud), patchouli, almizcle",
    imagen: "Bade%27e%20Al%20Oud%20Oud%20for%20Glory%20Lattafa%20Perfumes%20for%20women%20and%20men.avif"
  },
  {
    id: 23,
    activo: true,
    nombre: "Lattafa Raghba",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 30,
    notas: "Especias dulces, azúcar quemada / Oud, incienso / Vainilla, ámbar",
    imagen: "Lattafa%20Raghba.avif"
  },
  {
    id: 24,
    activo: true,
    nombre: "Lattafa Fakhar",
    tipo: "Árabe",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    precioUSD: 27,
    notas: "Manzana, jengibre, bergamota / Salvia, lavanda, enebro, geranio / Madera ambarada, haba tonka, cedro, vetiver",
    imagen: "Lattafa%20Fakhar.avif"
  },
  {
    id: 25,
    activo: true,
    nombre: "Armaf Club de Nuit Intense Man",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 40,
    notas: "Piña, manzana, limón, bergamota / Abedul, jazmín, especias / Almizcle, ámbar, pachulí",
    imagen: "Armaf%20Club%20de%20Nuit%20Intense%20Man.avif"
  },
  {
    id: 26,
    activo: true,
    nombre: "Armaf Club de Nuit Untold",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 43,
    notas: "Azafrán, jazmín / Madera ambarada, ámbar gris / Resina de abeto, cedro",
    imagen: "Armaf%20Club%20de%20Nuit%20Untold.avif"
  },
  {
    id: 27,
    activo: true,
    nombre: "Rasasi Hawas for Him",
    tipo: "Árabe",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    momento: "Deporte",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Económico",
    precioUSD: 36,
    notas: "Bergamota, manzana, canela, limón / Notas acuáticas, ciruela, azahar, cardamomo / Ámbar gris, almizcle, driftwood, patchouli",
    imagen: "Rasasi%20Hawas%20for%20Him.avif"
  },
  {
    id: 28,
    activo: true,
    nombre: "Rasasi Hawas Ice",
    tipo: "Árabe",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    momento: "Deporte",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Económico",
    precioUSD: 34,
    notas: "Manzana escarchada, bergamota italiana, limón italiano, anís estrellado / Ciruela, azahar, cardamomo, notas marinas / Almizcle, ámbar, driftwood, musgo",
    imagen: "Rasasi%20Hawas%20Ice.avif"
  },
  {
    id: 29,
    activo: true,
    nombre: "Afnan 9PM",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 31,
    notas: "Manzana, canela / Vainilla, haba tonka / Ámbar, almizcle, madera",
    imagen: "Afnan%209PM.avif"
  },
  {
    id: 30,
    activo: true,
    nombre: "Afnan Supremacy Not Only Intense",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 33,
    notas: "Grosella negra, bergamota, manzana / Musgo de encina, patchouli, lavanda / Ámbar gris, almizcle, azafrán",
    imagen: "Afnan%20Supremacy%20Not%20Only%20Intense.avif"
  },
  {
    id: 31,
    activo: true,
    nombre: "Al Haramain Amber Oud Gold",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 39,
    notas: "Bergamota, notas verdes / Melón, piña, notas dulces, ámbar / Madera, vainilla, almizcle",
    imagen: "Al%20Haramain%20Amber%20Oud%20Gold.avif"
  },
  {
    id: 32,
    activo: true,
    nombre: "Swiss Arabian Shaghaf Oud",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 44,
    notas: "Azafrán / Agarwood (oud), rosa / Agarwood (oud), praliné, vainilla",
    imagen: "Swiss%20Arabian%20Shaghaf%20Oud.avif"
  },
  {
    id: 33,
    activo: true,
    nombre: "Lattafa Ana Abiyedh",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    precioUSD: 25,
    notas: "Bergamota, naranja / Vainilla, pera / Almizcle, ámbar",
    imagen: "Lattafa%20Ana%20Abiyedh.avif"
  },
  {
    id: 34,
    activo: true,
    nombre: "Lattafa Qaa'ed",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    precioUSD: 30,
    notas: "Canela, cardamomo, bergamota / Azafrán, sándalo, cedro, clavel / Agarwood (oud), cuero, vainilla, ámbar",
    imagen: "data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%27http%3A//www.w3.org/2000/svg%27%20width%3D%27375%27%20height%3D%27500%27%20viewBox%3D%270%200%20375%20500%27%3E%0A%20%20%20%20%3Cdefs%3E%0A%20%20%20%20%20%20%3ClinearGradient%20id%3D%27g34%27%20x1%3D%270%27%20y1%3D%270%27%20x2%3D%270%27%20y2%3D%271%27%3E%0A%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%270%25%27%20stop-color%3D%27%231a1206%27/%3E%0A%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%27100%25%27%20stop-color%3D%27%232b1d08%27/%3E%0A%20%20%20%20%20%20%3C/linearGradient%3E%0A%20%20%20%20%3C/defs%3E%0A%20%20%20%20%3Crect%20width%3D%27375%27%20height%3D%27500%27%20fill%3D%27url%28%23g34%29%27/%3E%0A%20%20%20%20%3Cg%20fill%3D%27none%27%20stroke%3D%27%23efdc85%27%20stroke-width%3D%272%27%20opacity%3D%270.9%27%3E%0A%20%20%20%20%20%20%3Ccircle%20cx%3D%22187%22%20cy%3D%22245%22%20r%3D%2275%22/%3E%0A%20%20%20%20%20%20%3Crect%20x%3D%22167%22%20y%3D%22140%22%20width%3D%2240%22%20height%3D%2235%22%20rx%3D%225%22/%3E%0A%20%20%20%20%20%20%3Crect%20x%3D%22175%22%20y%3D%22118%22%20width%3D%2224%22%20height%3D%2224%22%20rx%3D%223%22/%3E%0A%20%20%20%20%3C/g%3E%0A%20%20%20%20%3Ctext%20x%3D%27187%27%20y%3D%27395%27%20font-family%3D%27Georgia%2C%20serif%27%20font-size%3D%2734%27%20font-weight%3D%27600%27%20fill%3D%27%23efdc85%27%20text-anchor%3D%27middle%27%20opacity%3D%270.9%27%3ELQ%3C/text%3E%0A%20%20%20%20%3Ctext%20x%3D%27187%27%20y%3D%27445%27%20font-family%3D%27Georgia%2C%20serif%27%20font-size%3D%2711%27%20letter-spacing%3D%272%27%20fill%3D%27%238a7d5f%27%20text-anchor%3D%27middle%27%3E%C3%81RABE%3C/text%3E%0A%20%20%3C/svg%3E"
  },
  {
    id: 35,
    activo: true,
    nombre: "Al Haramain L'Aventure",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 28,
    notas: "Limón, bergamota, elemi / Notas amaderadas, jazmín, muguet / Almizcle, patchouli, ámbar",
    imagen: "Al%20Haramain%20L%27Aventure.avif"
  },
  {
    id: 36,
    activo: true,
    nombre: "Lattafa Fakhar Rose",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Fiesta",
    clima: "Templado",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 27,
    notas: "Frutas, lirio, granada, aldehídos / Tuberosa, jazmín, gardenia, ylang-ylang, rosa, madreselva, peonía / Vainilla, almizcle blanco, sándalo, ambroxan",
    imagen: "Lattafa%20Fakhar%20Rose.avif"
  },

  // ================= LUJO / NICHO (14) =================
  {
    id: 37,
    activo: true,
    nombre: "Maison Francis Kurkdjian Baccarat Rouge 540",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 325,
    notas: "Azafrán, jazmín / Madera ambarada, ámbar gris, hedione / Resina de abeto, cedro, azúcar, ambroxan, musgo de encina",
    imagen: "Maison%20Francis%20Kurkdjian%20Baccarat%20Rouge%20540.avif"
  },
  {
    id: 38,
    activo: true,
    nombre: "Tom Ford Tobacco Vanille",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Tabaco dulce",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 218,
    notas: "Flor de tabaco, especias, jengibre / Haba tonka, especias, hoja de tabaco / Cacao, ámbar, vainilla, benjuí",
    imagen: "Tom%20Ford%20Tobacco%20Vanille.avif"
  },
  {
    id: 39,
    activo: true,
    nombre: "Tom Ford Oud Wood",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 240,
    notas: "Cardamomo, especias chinas / Oud, sándalo, palo de rosa / Vetiver, ámbar",
    imagen: "Tom%20Ford%20Oud%20Wood.avif"
  },
  {
    id: 40,
    activo: true,
    nombre: "Le Labo Santal 33",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 210,
    notas: "Cardamomo, iris, violeta / Cedro, sándalo / Almizcle, cuero, ámbar",
    imagen: "Le%20Labo%20Santal%2033.avif"
  },
  {
    id: 41,
    activo: true,
    nombre: "Creed Aventus",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 335,
    notas: "Piña, bergamota, manzana negra / Abedul, pachulí, rosa / Almizcle, roble, ámbar, vainilla",
    imagen: "Creed%20Aventus.avif"
  },
  {
    id: 42,
    activo: true,
    nombre: "Parfums de Marly Layton",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 195,
    notas: "Manzana, bergamota, lavanda / Especias, geranio / Vainilla, ámbar, almizcle",
    imagen: "Parfums%20de%20Marly%20Layton.avif"
  },
  {
    id: 43,
    activo: true,
    nombre: "Xerjoff Alexandria II",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 310,
    notas: "Palisandro, lavanda, manzana, canela / Rosa, cedro, muguet / Agarwood (oud), sándalo, ámbar, vainilla, almizcle",
    imagen: "Xerjoff%20Alexandria%20II.avif"
  },
  {
    id: 44,
    activo: true,
    nombre: "Amouage Interlude Man",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 285,
    notas: "Bergamota, orégano, pimienta de Jamaica / Ámbar, incienso, cistus, opoponax / Cuero, agarwood ahumado, patchouli, sándalo",
    imagen: "Amouage%20Interlude%20Man.avif"
  },
  {
    id: 45,
    activo: true,
    nombre: "Acqua di Parma Colonia",
    tipo: "Lujo",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Suave",
    presupuesto: "Sin límite",
    precioUSD: 165,
    notas: "Cítricos, bergamota / Lavanda, romero, verbena / Almizcle, madera, vetiver",
    imagen: "Acqua%20di%20Parma%20Colonia.avif"
  },
  {
    id: 46,
    activo: true,
    nombre: "Escentric Molecules Molecule 01",
    tipo: "Lujo",
    aromaPrincipal: "Limpio / Empolvado",
    subAroma: "Jabón fino",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Suave",
    presupuesto: "Sin límite",
    precioUSD: 138,
    notas: "Iso E Super — nota única sintética, aroma amaderado-ambarado muy cercano a la piel",
    imagen: "Escentric%20Molecules%20Molecule%2001.avif"
  },
  {
    id: 47,
    activo: true,
    nombre: "Guerlain L'Homme Idéal",
    tipo: "Lujo",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Postre / Vainilla",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 132,
    notas: "Cítricos, naranja amarga, romero, azahar / Almendra, haba tonka / Cuero, cedro, vetiver",
    imagen: "L%27Homme%20Id%C3%A9al%20Guerlain%20for%20men.avif"
  },
  {
    id: 48,
    activo: true,
    nombre: "Montblanc Explorer",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 95,
    notas: "Bergamota, pomarosa, salvia / Vetiver, cuero, sándalo / Patchouli, ámbar, madera",
    imagen: "Montblanc%20Explorer.avif"
  },
  {
    id: 49,
    activo: true,
    nombre: "Cartier Pasha de Cartier Parfum",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 155,
    notas: "Sándalo, licor, bálsamo de abeto / Benzoína, haba tonka, ambrocenide / Hoja de patchouli indonesio, labdanum",
    imagen: "Cartier%20Pasha%20de%20Cartier%20Parfum.avif"
  },
  {
    id: 50,
    activo: true,
    nombre: "Diptyque Eau Capitale",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Suave",
    presupuesto: "Sin límite",
    precioUSD: 175,
    notas: "Pimienta rosa, bergamota / Rosa, ylang-ylang, canela / Patchouli, musgo, madera",
    imagen: "Diptyque%20Eau%20Capitale.avif"
  }
,
  {
    id: 51,
    activo: true,
    nombre: "Giorgio Armani Code",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 74,
    notas: "Limón, bergamota / Anís estrellado, flor de olivo / Cuero, haba tonka",
    imagen: "Giorgio%20Armani%20Code.avif"
  },
  {
    id: 52,
    activo: true,
    nombre: "Chanel Bleu de Chanel EDT",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 98,
    notas: "Limón, menta, pomelo / Jengibre, nuez moscada / Incienso, cedro, sándalo",
    imagen: "Chanel%20Bleu%20de%20Chanel%20EDT.avif"
  },
  {
    id: 53,
    activo: true,
    nombre: "Prada Luna Rossa Carbon",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 95,
    notas: "Bergamota, pimienta, notas cítricas / Lavanda, geranio / Ambroxan, patchouli",
    imagen: "Prada%20Luna%20Rossa%20Carbon.avif"
  },
  {
    id: 54,
    activo: true,
    nombre: "Versace Dylan Blue",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 54,
    notas: "Toronja, higo de mar / Ambroxan, pimienta / Musgo de encina, pachulí",
    imagen: "Versace%20Dylan%20Blue.avif"
  },
  {
    id: 55,
    activo: true,
    nombre: "Montblanc Legend",
    tipo: "Diseñador",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 48,
    notas: "Bergamota, piña / Lavanda, geranio / Haba tonka, sándalo",
    imagen: "Montblanc%20Legend.avif"
  },
  {
    id: 56,
    activo: true,
    nombre: "Azzaro The Most Wanted",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    precioUSD: 68,
    notas: "Cardamomo / Toffee / Madera ambarada",
    imagen: "Azzaro%20The%20Most%20Wanted.avif"
  },
  {
    id: 57,
    activo: true,
    nombre: "Yves Saint Laurent La Nuit de l'Homme",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 88,
    notas: "Cardamomo, bergamota / Lavanda, cedro / Haba tonka, vetiver",
    imagen: "Yves%20Saint%20Laurent%20La%20Nuit%20de%20l%27Homme.avif"
  },
  {
    id: 58,
    activo: true,
    nombre: "Dolce & Gabbana Light Blue",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Suave",
    presupuesto: "Medio",
    precioUSD: 72,
    notas: "Manzana, limón siciliano / Jazmín, junco / Cedro, almizcle",
    imagen: "Dolce%20%26%20Gabbana%20Light%20Blue.avif"
  },
  {
    id: 59,
    activo: true,
    nombre: "Burberry Hero",
    tipo: "Diseñador",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 79,
    notas: "Bergamota / Enebro, pimienta negra / Cedro Atlas, cedro Virginia, cedro Himalaya",
    imagen: "Burberry%20Hero.avif"
  },
  {
    id: 60,
    activo: true,
    nombre: "Guerlain Habit Rouge",
    tipo: "Diseñador",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 92,
    notas: "Limón, palo de rosa brasileño, naranja, bergamota / Rosa, clavel, sándalo, canela, pachulí, jazmín, cedro / Vainilla, cuero, benjuí, ámbar, musgo de encina",
    imagen: "Guerlain%20Habit%20Rouge.avif"
  },
  {
    id: 61,
    activo: true,
    nombre: "Tom Ford Noir Extreme",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 155,
    notas: "Cardamomo, nuez moscada / Rosa, jengibre / Ámbar, vainilla, cacao",
    imagen: "Tom%20Ford%20Noir%20Extreme.avif"
  },
  {
    id: 62,
    activo: true,
    nombre: "Paco Rabanne 1 Million",
    tipo: "Diseñador",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    precioUSD: 76,
    notas: "Toronja, menta / Canela, especias / Cuero, ámbar, madera blanca",
    imagen: "Paco%20Rabanne%201%20Million.avif"
  },
  {
    id: 63,
    activo: true,
    nombre: "Jean Paul Gaultier Le Male",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 82,
    notas: "Menta, lavanda / Canela, comino / Vainilla, sándalo, ámbar",
    imagen: "Le%20Male%20Jean%20Paul%20Gaultier%20for%20men.avif"
  },
  {
    id: 64,
    activo: true,
    nombre: "Dior Homme Intense",
    tipo: "Diseñador",
    aromaPrincipal: "Limpio / Empolvado",
    subAroma: "Iris elegante",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 105,
    notas: "Lavanda, iris / Cacao, ámbar / Cedro, vetiver",
    imagen: "Dior%20Homme%20Intense.avif"
  },
  {
    id: 65,
    activo: true,
    nombre: "Versace Eros Flame",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Fiesta",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    precioUSD: 71,
    notas: "Pimienta negra, mandarina / Especias, canela / Haba tonka, madera de Bengala",
    imagen: "Versace%20Eros%20Flame.avif"
  },
  {
    id: 66,
    activo: true,
    nombre: "Lattafa Khamrah Qahwa",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 34,
    notas: "Café, canela / Dátiles, especias / Ámbar, vainilla, oud",
    imagen: "Lattafa%20Khamrah%20Qahwa.avif"
  },
  {
    id: 67,
    activo: true,
    nombre: "Lattafa Khamrah Dukhan",
    tipo: "Árabe",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Tabaco dulce",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 36,
    notas: "Especias, pimento, mandarina / Incienso, labdanum, azahar, patchouli / Praliné, tabaco, ámbar, haba tonka, benzoína",
    imagen: "Lattafa%20Khamrah%20Dukhan.avif"
  },
  {
    id: 68,
    activo: true,
    nombre: "Lattafa Asad Bourbon",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 31,
    notas: "Ron bourbon, piña / Canela, especias / Ámbar, madera, vainilla",
    imagen: "Lattafa%20Asad%20Bourbon.avif"
  },
  {
    id: 69,
    activo: true,
    nombre: "Afnan Supremacy Collector's Edition",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 42,
    notas: "Piña, bergamota / Abedul, especias / Ámbar, almizcle, oud",
    imagen: "Afnan%20Supremacy%20Collector%27s%20Edition.avif"
  },
  {
    id: 70,
    activo: true,
    nombre: "Armaf Odyssey Mandarin Sky",
    tipo: "Árabe",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    precioUSD: 38,
    notas: "Mandarina, bergamota / Jazmín, especias / Almizcle, madera clara",
    imagen: "Armaf%20Odyssey%20Mandarin%20Sky.avif"
  },
  {
    id: 71,
    activo: true,
    nombre: "Lattafa Opulent Dubai",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Fiesta",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 37,
    notas: "Mango, toronja, limón, jengibre / Jazmín, cedro, violeta / Ámbar gris, madera, musgo, benzoína",
    imagen: "Lattafa%20Opulent%20Dubai.avif"
  },
  {
    id: 72,
    activo: true,
    nombre: "Dior Sauvage Elixir Intense",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 165,
    notas: "Nuez moscada, cardamomo, canela, toronja / Lavanda, coumarina / Regaliz, sándalo, ámbar, vetiver, patchouli",
    imagen: "Dior%20Sauvage%20Elixir%20Intense.avif"
  },
  {
    id: 73,
    activo: true,
    nombre: "Tom Ford Ombré Leather Parfum",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 245,
    notas: "Cardamomo, azafrán / Cuero, jazmín / Ámbar, cuero, almizcle",
    imagen: "Tom%20Ford%20Ombr%C3%A9%20Leather%20Parfum.avif"
  },
  {
    id: 74,
    activo: true,
    nombre: "Creed Aventus Cologne",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 290,
    notas: "Mandarina, jengibre, pimienta rosa, bergamota / Vetiver, patchouli, sándalo, piña / Almizcle, haba tonka, styrax, abedul",
    imagen: "Creed%20Aventus%20Cologne.avif"
  },
  {
    id: 75,
    activo: true,
    nombre: "Parfums de Marly Herod",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 310,
    notas: "Canela, pimienta / Osmanthus, hoja de tabaco, labdanum, incienso / Vainilla, cedro, vetiver, patchouli, almizcle",
    imagen: "Parfums%20de%20Marly%20Herod.avif"
  },
  {
    id: 76,
    activo: true,
    nombre: "Xerjoff Erba Pura",
    tipo: "Lujo",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 225,
    notas: "Naranja siciliana, bergamota de Calabria, limón siciliano / Frutas mediterráneas / Almizcle blanco, vainilla de Madagascar, ámbar",
    imagen: "Erba%20Pura%20Xerjoff.avif"
  },
  {
    id: 77,
    activo: true,
    nombre: "Amouage Reflection Man",
    tipo: "Lujo",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 245,
    notas: "Romero, pimienta rosa, petitgrain / Jazmín, neroli, iris, ylang-ylang / Sándalo, cedro, vetiver, patchouli",
    imagen: "Amouage%20Reflection%20Man.avif"
  },
  {
    id: 78,
    activo: true,
    nombre: "Initio Oud for Greatness",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 295,
    notas: "Azafrán, nuez moscada, lavanda / Agarwood (oud) / Patchouli, almizcle",
    imagen: "Oud%20for%20Greatness%20Initio%20Parfums%20Prives%20for%20women%20and%20men.avif"
  },
  {
    id: 79,
    activo: true,
    nombre: "Nishane Hacivat",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 270,
    notas: "Piña, bergamota, toronja / Jazmín, oakmoss / Patchouli",
    imagen: "Nishane%20Hacivat.avif"
  },
  {
    id: 80,
    activo: true,
    nombre: "Byredo Bal d'Afrique",
    tipo: "Lujo",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Suave",
    presupuesto: "Sin límite",
    precioUSD: 210,
    notas: "Bergamota, limón, neroli, caléndula africana, bucchu / Violeta, jazmín, ciclamen / Ámbar negro, almizcle, vetiver, cedro marroquí",
    imagen: "Byredo%20Bal%20d%27Afrique.avif"
  },
  {
    id: 81,
    activo: true,
    nombre: "Rasasi Hawas Elixir",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 38,
    notas: "Menta, bergamota, artemisa / Chocolate oscuro, lavanda, benzoína / Vainilla, haba tonka, almizcle blanco",
    imagen: "Rasasi%20Hawas%20Elixir.avif"
  },
  {
    id: 82,
    activo: true,
    nombre: "Al Haramain L'Aventure Fraiche",
    tipo: "Árabe",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    precioUSD: 33,
    notas: "Limón, jengibre / Té, cardamomo / Almizcle, sándalo, madera",
    imagen: "Al%20Haramain%20L%27Aventure%20Fraiche.avif"
  },
  {
    id: 83,
    activo: true,
    nombre: "Lattafa Yara Tous",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 29,
    notas: "Fruta de la pasión, pera / Orquídea, flores blancas / Almizcle, vainilla, praliné",
    imagen: "Yara%20Tous%20Lattafa%20Perfumes%20for%20women.avif"
  },
  {
    id: 84,
    activo: true,
    nombre: "Armaf Club de Nuit Sillage",
    tipo: "Árabe",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 45,
    notas: "Bergamota, limón, lima, grosella negra, hoja de violeta, jengibre / Rosa, iris, jazmín / Ambroxan, almizcle, sándalo, cedro",
    imagen: "Armaf%20Club%20de%20Nuit%20Sillage.avif"
  },
  {
    id: 85,
    activo: true,
    nombre: "Swiss Arabian Shaghaf Oud Elixir",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 41,
    notas: "Oud, azafrán, pimienta rosa / Praliné, rosa, salvia / Vainilla, ámbar, almizcle",
    imagen: "Shaghaf%20Oud%20Elixir%20Swiss%20Arabian%20for%20women%20and%20men.avif"
  },
  {
    id: 86,
    activo: true,
    nombre: "Lattafa Fakhar Black",
    tipo: "Árabe",
    aromaPrincipal: "Limpio / Empolvado",
    subAroma: "Jabón fino",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    precioUSD: 28,
    notas: "Manzana, bergamota, jengibre / Lavanda, salvia / Haba tonka, cedro, vetiver",
    imagen: "Lattafa%20Fakhar%20Black.avif"
  },
  {
    id: 87,
    activo: true,
    nombre: "Al Haramain Amber Oud Tobacco Edition",
    tipo: "Árabe",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Tabaco dulce",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 43,
    notas: "Tabaco, especias dulces / Oud, cacao / Vainilla, ámbar, madera",
    imagen: "Al%20Haramain%20Amber%20Oud%20Tobacco%20Edition.avif"
  },
  {
    id: 88,
    activo: true,
    nombre: "Lattafa Qaa'ed Intense",
    tipo: "Árabe",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Tabaco dulce",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 32,
    notas: "Tabaco, canela, miel blanca / Vainilla, cacao, mirra / Ámbar, labdanum, styrax",
    imagen: "Qaa%27ed%20Intense%20Lattafa%20Perfumes%20for%20men.avif"
  },
  {
    id: 89,
    activo: true,
    nombre: "Afnan 9PM Femme",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 30,
    notas: "Frambuesa, violeta, manzana, naranja / Rosa, peonía, iris, jazmín / Ciprés, pino, ámbar, cedro",
    imagen: "Afnan%209PM%20Femme.avif"
  },
  {
    id: 90,
    activo: true,
    nombre: "Ard Al Zaafaran Aicha",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Diario",
    clima: "Templado",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Económico",
    precioUSD: 24,
    notas: "Frutas rojas, bergamota / Rosa, jazmín / Almizcle, vainilla, madera clara",
    imagen: "data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%27http%3A//www.w3.org/2000/svg%27%20width%3D%27375%27%20height%3D%27500%27%20viewBox%3D%270%200%20375%20500%27%3E%0A%20%20%20%20%3Cdefs%3E%0A%20%20%20%20%20%20%3ClinearGradient%20id%3D%27g90%27%20x1%3D%270%27%20y1%3D%270%27%20x2%3D%270%27%20y2%3D%271%27%3E%0A%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%270%25%27%20stop-color%3D%27%231a1206%27/%3E%0A%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%27100%25%27%20stop-color%3D%27%232b1d08%27/%3E%0A%20%20%20%20%20%20%3C/linearGradient%3E%0A%20%20%20%20%3C/defs%3E%0A%20%20%20%20%3Crect%20width%3D%27375%27%20height%3D%27500%27%20fill%3D%27url%28%23g90%29%27/%3E%0A%20%20%20%20%3Cg%20fill%3D%27none%27%20stroke%3D%27%23d6c174%27%20stroke-width%3D%272%27%20opacity%3D%270.9%27%3E%0A%20%20%20%20%20%20%3Crect%20x%3D%22138%22%20y%3D%22165%22%20width%3D%2299%22%20height%3D%22155%22%20rx%3D%228%22/%3E%0A%20%20%20%20%20%20%3Crect%20x%3D%22158%22%20y%3D%22128%22%20width%3D%2259%22%20height%3D%2242%22%20rx%3D%225%22/%3E%0A%20%20%20%20%20%20%3Crect%20x%3D%22168%22%20y%3D%22112%22%20width%3D%2239%22%20height%3D%2220%22%20rx%3D%223%22/%3E%0A%20%20%20%20%20%20%3Cline%20x1%3D%22138%22%20y1%3D%22215%22%20x2%3D%22237%22%20y2%3D%22215%22/%3E%0A%20%20%20%20%20%20%3Cline%20x1%3D%22138%22%20y1%3D%22255%22%20x2%3D%22237%22%20y2%3D%22255%22/%3E%0A%20%20%20%20%3C/g%3E%0A%20%20%20%20%3Ctext%20x%3D%27187%27%20y%3D%27395%27%20font-family%3D%27Georgia%2C%20serif%27%20font-size%3D%2734%27%20font-weight%3D%27600%27%20fill%3D%27%23d6c174%27%20text-anchor%3D%27middle%27%20opacity%3D%270.9%27%3EAA%3C/text%3E%0A%20%20%20%20%3Ctext%20x%3D%27187%27%20y%3D%27445%27%20font-family%3D%27Georgia%2C%20serif%27%20font-size%3D%2711%27%20letter-spacing%3D%272%27%20fill%3D%27%238a7d5f%27%20text-anchor%3D%27middle%27%3E%C3%81RABE%3C/text%3E%0A%20%20%3C/svg%3E"
  },
  {
    id: 91,
    activo: true,
    nombre: "Kilian Angel's Share",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 250,
    notas: "Coñac, canela / Roble, nuez moscada / Haba tonka, sándalo",
    imagen: "Kilian%20Angel%27s%20Share.avif"
  },
  {
    id: 92,
    activo: true,
    nombre: "Roja Parfums Elysium",
    tipo: "Lujo",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 340,
    notas: "Bergamota, limón / Salvia, geranio / Almizcle, vetiver, ámbar",
    imagen: "Roja%20Parfums%20Elysium.avif"
  },
  {
    id: 93,
    activo: true,
    nombre: "Mancera Cedrat Boise",
    tipo: "Lujo",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 180,
    notas: "Cedrat, bergamota / Cedro, jazmín / Almizcle, ámbar",
    imagen: "Mancera%20Cedrat%20Boise.avif"
  },
  {
    id: 94,
    activo: true,
    nombre: "Montale Intense Café",
    tipo: "Lujo",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 195,
    notas: "Café, canela / Chocolate, cacao / Vainilla, ámbar, madera",
    imagen: "Montale%20Intense%20Caf%C3%A9.avif"
  },
  {
    id: 95,
    activo: true,
    nombre: "Xerjoff Naxos",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Tabaco dulce",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 260,
    notas: "Bergamota, lavanda / Miel, tabaco / Haba tonka, vainilla, sándalo",
    imagen: "Xerjoff%20Naxos.avif"
  },
  {
    id: 96,
    activo: true,
    nombre: "Amouage Interlude Woman",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 280,
    notas: "Incienso, bergamota / Jazmín, clavo / Pachulí, oud, ámbar",
    imagen: "Amouage%20Interlude%20Woman.avif"
  },
  {
    id: 97,
    activo: true,
    nombre: "Parfums de Marly Percival",
    tipo: "Lujo",
    aromaPrincipal: "Limpio / Empolvado",
    subAroma: "Jabón fino",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 225,
    notas: "Manzana, bergamota / Lavanda, geranio / Almizcle, sándalo, vainilla",
    imagen: "Parfums%20de%20Marly%20Percival.avif"
  },
  {
    id: 98,
    activo: true,
    nombre: "Louis Vuitton Ombre Nomade",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 350,
    notas: "Oud, incienso / Cera de abejas, jazmín / Ámbar, resinas, madera",
    imagen: "Louis%20Vuitton%20Ombre%20Nomade.avif"
  },
  {
    id: 99,
    activo: true,
    nombre: "Bvlgari Man in Black",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 135,
    notas: "Especias, ron / Cuero, tabaco / Haba tonka, ámbar, cuero",
    imagen: "Bvlgari%20Man%20in%20Black.avif"
  },
  {
    id: 100,
    activo: true,
    nombre: "Maison Francis Kurkdjian Grand Soir",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    precioUSD: 300,
    notas: "Ámbar, vainilla / Haba tonka, benzoína / Ládano, almizcle, madera",
    imagen: "Maison%20Francis%20Kurkdjian%20Grand%20Soir.avif"
  }
,
  {
    id: 101,
    activo: true,
    nombre: "Afnan 9PM Night Out",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 31,
    notas: "Fruta de dragón, bergamota, coñac, lavanda, manzana / Cardamomo, ante, toffee, cedro / Haba tonka, akigalawood, patchouli",
    imagen: "Afnan%209PM%20Night%20Out.avif"
  }
,
  {
    id: 102,
    activo: true,
    nombre: "Paco Rabanne 1 Million Lucky",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Citas",
    clima: "Templado",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 73,
    notas: "Toronja, mandarina / Avellana, almendra / Haba tonka, madera blanca",
    imagen: "Paco%20Rabanne%201%20Million%20Lucky.avif"
  }
,
  {
    id: 103,
    activo: true,
    nombre: "Jean Paul Gaultier Le Male Le Parfum",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    precioUSD: 98,
    notas: "Lavanda, vainilla / Especias, cacao / Haba tonka, ámbar, madera",
    imagen: "Le%20Male%20Le%20Parfum%20Jean%20Paul%20Gaultier%20for%20men.avif"
  },
  {
    id: 104,
    activo: true,
    nombre: "Jean Paul Gaultier Le Male Elixir Absolu",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    precioUSD: 105,
    notas: "Lavanda, menta / Vainilla intensa, benzoína / Miel, tabaco, haba tonka concentrada",
    imagen: "Jean%20Paul%20Gaultier%20Le%20Male%20Elixir%20Absolu.avif"
  },
  {
    id: 105,
    activo: true,
    nombre: "Jean Paul Gaultier Le Beau Paradise Garden",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 89,
    notas: "Notas verdes, notas acuáticas, menta, jengibre / Coco, higo, sal / Haba tonka, sándalo",
    imagen: "Jean%20Paul%20Gaultier%20Le%20Male%20Paradise%20Garden.avif"
  },
  {
    id: 106,
    activo: true,
    nombre: "Jean Paul Gaultier Le Beau",
    tipo: "Diseñador",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    precioUSD: 82,
    notas: "Bergamota, coco / Sándalo, haba tonka / Almizcle, madera de cachemira",
    imagen: "Jean%20Paul%20Gaultier%20Le%20Beau.avif"
  }
,
  {
    id: 107,
    activo: true,
    nombre: "Xerjoff Torino 21",
    tipo: "Lujo",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 255,
    notas: "Menta, limón, albahaca, tomillo / Grosella negra, lavanda, romero, jazmín / Almizcle, verbena",
    imagen: "Torino%2021.avif"
  },
  {
    id: 108,
    activo: true,
    nombre: "Armaf Club de Nuit Urban Man Elixir",
    tipo: "Árabe",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 39,
    notas: "Bergamota, pimienta rosa / Lavanda, azafrán / Ambroxan, ámbar, cedro",
    imagen: "Armaf%20Club%20de%20Nuit%20Urban%20Man%20Elixir.avif"
  }
,
  {
    id: 109,
    activo: true,
    nombre: "Louis Vuitton L'Immensité",
    tipo: "Lujo",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 345,
    notas: "Toronja, jengibre, bergamota / Notas acuáticas, salvia, romero, geranio / Ambroxan, ámbar, labdanum",
    imagen: "L%27Immensit%C3%A9.avif"
  },
  {
    id: 110,
    activo: true,
    nombre: "Louis Vuitton Imagination",
    tipo: "Lujo",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    precioUSD: 345,
    notas: "Citrón, bergamota calabresa, naranja siciliana / Neroli, jengibre, canela / Té negro chino, ambroxan, guaiac wood, olíbano",
    imagen: "Imagination%20Louis%20Vuitton%20for%20men.avif"
  }
,
  {
    id: 111,
    activo: true,
    nombre: "French Avenue Vulcan Feu",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    momento: "Fiesta",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 40,
    notas: "Mango, jengibre, limón, frutos rojos / Cumarina, jazmín, cedro, pimienta rosa, violeta, praliné / Almizcle, ámbar, oud, cypriol, haba tonka",
    imagen: "French%20Avenue%20Vulcan%20Feu.avif"
  },
  {
    id: 112,
    activo: true,
    nombre: "Emporio Armani Stronger With You Intensely",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    precioUSD: 92,
    notas: "Pimienta rosa, enebro, violeta / Lavanda, salvia, toffee, canela / Cuero, ámbar, vainilla, haba tonka",
    imagen: "Emporio%20Armani%20Stronger%20With%20You%20Intensely.avif"
  }
,
  {
    id: 113,
    activo: true,
    nombre: "French Avenue Liquid Brun",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    precioUSD: 38,
    notas: "Canela, flor de naranjo, cardamomo, bergamota / Vainilla bourbon, elemi / Almizcle, praliné, ambroxan, guaiac wood",
    imagen: "French%20Avenue%20Liquid%20Brun.avif"
  }
];

// Fallback SVG (data URI) — se usa si la imagen real no carga
const FALLBACK_IMG =
  "data:image/svg+xml;utf8," +
  encodeURIComponent(`
  <svg xmlns='http://www.w3.org/2000/svg' width='375' height='500' viewBox='0 0 375 500'>
    <defs>
      <linearGradient id='g' x1='0' y1='0' x2='0' y2='1'>
        <stop offset='0%' stop-color='#1a1a1a'/>
        <stop offset='100%' stop-color='#2b2410'/>
      </linearGradient>
    </defs>
    <rect width='375' height='500' fill='url(#g)'/>
    <g fill='none' stroke='#ffb703' stroke-width='2' opacity='0.85'>
      <rect x='140' y='150' width='95' height='170' rx='10'/>
      <rect x='160' y='110' width='55' height='45' rx='6'/>
      <line x1='140' y1='210' x2='235' y2='210'/>
      <line x1='140' y1='250' x2='235' y2='250'/>
    </g>
    <text x='187' y='370' font-family='Georgia, serif' font-size='16' fill='#ffb703' text-anchor='middle'>Perfume</text>
    <text x='187' y='392' font-family='Georgia, serif' font-size='12' fill='#c9c9c9' text-anchor='middle'>Imagen no disponible</text>
  </svg>`);
