/* ============================================================
   BUSCADOR DE PERFUMES PRO — data.js
   Base de datos de 50 fragancias reales (Diseñador / Árabe / Lujo)
   Fuente: top50-perfumes-referencia.md (notas y familias verificadas)
   ============================================================ */

// Rangos de presupuesto en USD. Se usan para clasificar cada fragancia
// según su PRECIO DE VENTA y poder filtrar por presupuesto en el test.
//
// Los precios en sí NO viven en este archivo: son dato de negocio, se
// administran desde catalogo.html y se guardan en la base de datos. Aquí
// solo quedan los cortes de cada rango.
const RANGOS_PRECIO = {
  Económico: { min: 20, max: 45, etiqueta: "$20 – $45" },
  Medio: { min: 55, max: 110, etiqueta: "$55 – $110" },
  "Sin límite": { min: 130, max: 350, etiqueta: "$130 – $350+" }
};

const PERFUMES = [
  // ================= DISEÑADOR (18) =================
  {
    id: 1,
    activo: true,
    nombre: "Dior Sauvage EDT",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    notaEspecifica: "citrico-simple",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Bergamota de Calabria, pimienta / Lavanda, pachulí, vetiver / Ambroxan, cedro",
    imagen: "Dior%20Sauvage%20EDT.avif"
  },
  {
    id: 2,
    activo: true,
    nombre: "Dior Sauvage EDP",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    notaEspecifica: "citrico-simple",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Bergamota, pimienta rosa / Pimienta de Sichuan, lavanda, anís estrellado / Ambroxan, vainilla",
    imagen: "Dior%20Sauvage%20EDP.avif"
  },
  {
    id: 3,
    activo: true,
    nombre: "Dior Sauvage Elixir",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    notaEspecifica: "especiado-fresco",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Nuez moscada, canela, cardamomo / Lavanda, coumarina / Regaliz, sándalo, ámbar, pachulí",
    imagen: "Dior%20Sauvage%20Elixir.avif"
  },
  {
    id: 4,
    activo: true,
    nombre: "Chanel Bleu de Chanel EDP",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico verde / aromático",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Cítricos, menta / Jengibre, nuez moscada / Sándalo, incienso, cedro, labdanum",
    imagen: "Chanel%20Bleu%20de%20Chanel%20EDP.avif"
  },
  {
    id: 5,
    activo: true,
    nombre: "Versace Eros",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-tropical",
    momento: "Fiesta",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Menta, manzana verde, limón / Tonka, geranio, ambroxan / Vainilla, cedro, vetiver",
    imagen: "Versace%20Eros.avif"
  },
  {
    id: 6,
    activo: true,
    nombre: "Giorgio Armani Acqua di Giò",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    notaEspecifica: "marino-suave",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Notas marinas, bergamota, neroli / Jazmín, romero / Almizcle blanco, cedro, oakmoss",
    imagen: "Giorgio%20Armani%20Acqua%20di%20Gio.avif"
  },
  {
    id: 7,
    activo: true,
    nombre: "Yves Saint Laurent Y EDP",
    tipo: "Diseñador",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "cedro-citrico",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Manzana, bergamota, jengibre / Salvia, geranio, cedro / Ámbar madera, haba tonka",
    imagen: "Yves%20Saint%20Laurent%20Y%20EDP.avif"
  },
  {
    id: 8,
    activo: true,
    nombre: "Jean Paul Gaultier Le Male Elixir",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    notaEspecifica: "vainilla-especiada",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Lavanda, menta / Vainilla, benzoína / Miel, tabaco, haba tonka",
    imagen: "Le%20Male%20Elixir%20Jean%20Paul%20Gaultier%20for%20men.avif"
  },
  {
    id: 9,
    activo: true,
    nombre: "Paco Rabanne Invictus",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    notaEspecifica: "marino-intenso",
    momento: "Deporte",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Toronja, mandarina marina / Laurel, jazmín / Ámbar, guaiac wood, pachulí",
    imagen: "Paco%20Rabanne%20Invictus.avif"
  },
  {
    id: 10,
    activo: true,
    nombre: "Carolina Herrera CH Men Prive",
    tipo: "Diseñador",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    notaEspecifica: "cuero-fresco",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Whiskey, toronja, pomelo / Cardamomo, lavanda, salvia, tomillo rojo / Cuero, haba tonka, benzoína, madera",
    imagen: "Carolina%20Herrera%20CH%20Men%20Prive.avif"
  },
  {
    id: 11,
    activo: true,
    nombre: "Prada Candy",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    notaEspecifica: "vainilla-pura",
    momento: "Citas",
    clima: "Templado",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Caramelo / Almizcle blanco, benzoína / Haba tonka, vainilla",
    imagen: "Prada-Candy.avif"
  },
  {
    id: 12,
    activo: true,
    nombre: "Marc Jacobs Daisy",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-citrico",
    momento: "Diario",
    clima: "Templado",
    estilo: "Joven",
    potencia: "Suave",
    presupuesto: "Medio",
    notas: "Pomelo sangre, hoja de violeta, fresa / Violeta, jazmín, gardenia / Almizcle blanco, vainilla dulce",
    imagen: "Marc%20Jacobs%20Daisy.avif"
  },
  {
    id: 13,
    activo: true,
    nombre: "Lancôme La Vie Est Belle",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    notaEspecifica: "floral-dulce",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Grosella negra, pera / Iris, jazmín, azahar / Praliné, vainilla, pachulí",
    imagen: "Lanc%C3%B4me%20La%20Vie%20Est%20Belle.avif"
  },
  {
    id: 14,
    activo: true,
    nombre: "Yves Saint Laurent Opium",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "cafe-datiles",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Mandarina, ciruela, pimienta / Clavo, canela, jazmín / Pachulí, ámbar, vainilla, incienso",
    imagen: "Opium%20Eau%20de%20Parfum%202009%20Yves%20Saint%20Laurent%20for%20women.avif"
  },
  {
    id: 15,
    activo: true,
    nombre: "Davidoff Cool Water",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    notaEspecifica: "aromatico-herbal",
    momento: "Deporte",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Suave",
    presupuesto: "Económico",
    notas: "Lavanda, menta, romero / Jazmín, geranio, sándalo / Almizcle, tabaco, ámbar",
    imagen: "Davidoff%20Cool%20Water.avif"
  },
  {
    id: 16,
    activo: true,
    nombre: "Hugo Boss Bottled",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "vainilla-pura",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Manzana, ciruela, bergamota / Canela, geranio, clavo / Sándalo, cedro, vainilla",
    imagen: "Boss%20Bottled%20Hugo%20Boss%20for%20men.avif"
  },
  {
    id: 17,
    activo: true,
    nombre: "Ralph Lauren Polo Blue",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    notaEspecifica: "marino-suave",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Suave",
    presupuesto: "Medio",
    notas: "Melón, cítricos / Geranio, notas acuáticas / Almizcle, cedro",
    imagen: "Ralph%20Lauren%20Polo%20Blue.avif"
  },
  {
    id: 18,
    activo: true,
    nombre: "Calvin Klein CK One",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    notaEspecifica: "citrico-simple",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Suave",
    presupuesto: "Económico",
    notas: "Bergamota, cardamomo, piña / Notas florales, nuez moscada / Almizcle, ámbar",
    imagen: "Calvin%20klein%20One%20Essence.avif"
  },

  // ================= ÁRABE (18) =================
  {
    id: 19,
    activo: true,
    nombre: "Lattafa Khamrah",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "cafe-datiles",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Canela, dátiles / Vainilla, praliné / Ámbar, especias, oud",
    imagen: "Khamrah%20Lattafa%20Perfumes%20for%20women%20and%20men.avif"
  },
  {
    id: 20,
    activo: true,
    nombre: "Lattafa Yara",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-tropical",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Fruta de la pasión, pera, mandarina / Orquídea, jazmín, gardenia / Almizcle, vainilla, sándalo",
    imagen: "Lattafa%20Yara.avif"
  },
  {
    id: 21,
    activo: true,
    nombre: "Lattafa Asad",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    notaEspecifica: "especiado-intenso",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Pimienta negra, tabaco, piña / Patchouli, café, iris / Vainilla, ámbar, madera seca, benzoína, labdanum",
    imagen: "Lattafa%20Asad.avif"
  },
  {
    id: 22,
    activo: true,
    nombre: "Lattafa Bade'e Al Oud \"Oud For Glory\"",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-dulce",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Azafrán, nuez moscada, lavanda / Agarwood (oud), patchouli / Agarwood (oud), patchouli, almizcle",
    imagen: "Bade%27e%20Al%20Oud%20Oud%20for%20Glory%20Lattafa%20Perfumes%20for%20women%20and%20men.avif"
  },
  {
    id: 23,
    activo: true,
    nombre: "Lattafa Raghba",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-resinoso",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Especias dulces, azúcar quemada / Oud, incienso / Vainilla, ámbar",
    imagen: "Lattafa%20Raghba.avif"
  },
  {
    id: 24,
    activo: true,
    nombre: "Lattafa Art of Universe",
    tipo: "Árabe",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    notaEspecifica: "menta-dominante",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Mandarina, jengibre, bergamota, menta / Pera, azahar / Almizcle, ámbar, cedro",
    imagen: "Lattafa%20Art%20of%20Universe.avif"
  },
  {
    id: 25,
    activo: true,
    nombre: "Armaf Club de Nuit Intense Man",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "cedro-citrico",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Piña, manzana, limón, bergamota / Abedul, jazmín, especias / Almizcle, ámbar, pachulí",
    imagen: "Armaf%20Club%20de%20Nuit%20Intense%20Man.avif"
  },
  {
    id: 26,
    activo: false,
    nombre: "Armaf Club de Nuit Untold",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-resinoso",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Azafrán, jazmín / Madera ambarada, ámbar gris / Resina de abeto, cedro",
    imagen: "Armaf%20Club%20de%20Nuit%20Untold.avif"
  },
  {
    id: 27,
    activo: true,
    nombre: "Rasasi Hawas for Him",
    tipo: "Árabe",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    notaEspecifica: "marino-intenso",
    momento: "Deporte",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Bergamota, manzana, canela, limón / Notas acuáticas, ciruela, azahar, cardamomo / Ámbar gris, almizcle, driftwood, patchouli",
    imagen: "Rasasi%20Hawas%20for%20Him.avif"
  },
  {
    id: 28,
    activo: true,
    nombre: "Rasasi Hawas Ice",
    tipo: "Árabe",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    notaEspecifica: "menta-dominante",
    momento: "Deporte",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Manzana escarchada, bergamota italiana, limón italiano, anís estrellado / Ciruela, azahar, cardamomo, notas marinas / Almizcle, ámbar, driftwood, musgo",
    imagen: "Rasasi%20Hawas%20Ice.avif"
  },
  {
    id: 29,
    activo: true,
    nombre: "Afnan 9PM",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "canela-clasica",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Manzana, canela / Vainilla, haba tonka / Ámbar, almizcle, madera",
    imagen: "Afnan%209PM.avif"
  },
  {
    id: 30,
    activo: true,
    nombre: "Afnan Turathi Electric",
    tipo: "Árabe",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    notaEspecifica: "citrico-flor-madera",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Pera, mandarina, toronja rosa, bergamota / Azahar, manzana, cedro / Almizcle, ámbar, vainilla",
    imagen: "Afnan%20Turathi%20Electric.avif"
  },
  {
    id: 31,
    activo: true,
    nombre: "Al Haramain Amber Oud Gold",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-tropical",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Bergamota, notas verdes / Melón, piña, notas dulces, ámbar / Madera, vainilla, almizcle",
    imagen: "Al%20Haramain%20Amber%20Oud%20Gold.avif"
  },
  {
    id: 32,
    activo: true,
    nombre: "Swiss Arabian Shaghaf Oud",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-dulce",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Azafrán / Agarwood (oud), rosa / Agarwood (oud), praliné, vainilla",
    imagen: "Swiss%20Arabian%20Shaghaf%20Oud.avif"
  },
  {
    id: 33,
    activo: true,
    nombre: "Lattafa Ana Abiyedh",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-citrico",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Bergamota, naranja / Vainilla, pera / Almizcle, ámbar",
    imagen: "Lattafa%20Ana%20Abiyedh.avif"
  },
  {
    id: 34,
    activo: true,
    nombre: "Lattafa Qaa'ed",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-dulce",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Canela, cardamomo, bergamota / Azafrán, sándalo, cedro, clavel / Agarwood (oud), cuero, vainilla, ámbar",
    imagen: "Lattafa%20Qaaed.avif"
  },
  {
    id: 35,
    activo: true,
    nombre: "Al Haramain L'Aventure",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "sandalo-limpio",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Limón, bergamota, elemi / Notas amaderadas, jazmín, muguet / Almizcle, patchouli, ámbar",
    imagen: "Al%20Haramain%20L%27Aventure.avif"
  },
  {
    id: 36,
    activo: true,
    nombre: "Lattafa Fakhar Rose",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "floral-dulce",
    momento: "Fiesta",
    clima: "Templado",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Frutas, lirio, granada, aldehídos / Tuberosa, jazmín, gardenia, ylang-ylang, rosa, madreselva, peonía / Vainilla, almizcle blanco, sándalo, ambroxan",
    imagen: "Lattafa%20Fakhar%20Rose.avif"
  },

  // ================= LUJO / NICHO (14) =================
  {
    id: 37,
    activo: true,
    nombre: "Maison Francis Kurkdjian Baccarat Rouge 540",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    notaEspecifica: "ambar-resina",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Azafrán, jazmín / Madera ambarada, ámbar gris, hedione / Resina de abeto, cedro, azúcar, ambroxan, musgo de encina",
    imagen: "Maison%20Francis%20Kurkdjian%20Baccarat%20Rouge%20540.avif"
  },
  {
    id: 38,
    activo: true,
    nombre: "Tom Ford Tobacco Vanille",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Tabaco dulce",
    notaEspecifica: "tabaco-cacao",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Flor de tabaco, especias, jengibre / Haba tonka, especias, hoja de tabaco / Cacao, ámbar, vainilla, benjuí",
    imagen: "Tom%20Ford%20Tobacco%20Vanille.avif"
  },
  {
    id: 39,
    activo: true,
    nombre: "Tom Ford Oud Wood",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-resinoso",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Cardamomo, especias chinas / Oud, sándalo, palo de rosa / Vetiver, ámbar",
    imagen: "Tom%20Ford%20Oud%20Wood.avif"
  },
  {
    id: 40,
    activo: true,
    nombre: "Le Labo Santal 33",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "sandalo-floral",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Cardamomo, iris, violeta / Cedro, sándalo / Almizcle, cuero, ámbar",
    imagen: "Le%20Labo%20Santal%2033.avif"
  },
  {
    id: 41,
    activo: true,
    nombre: "Creed Aventus",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "cedro-citrico",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Piña, bergamota, manzana negra / Abedul, pachulí, rosa / Almizcle, roble, ámbar, vainilla",
    imagen: "Creed%20Aventus.avif"
  },
  {
    id: 42,
    activo: true,
    nombre: "Parfums de Marly Layton",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "especiado-intenso",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Manzana, bergamota, lavanda / Especias, geranio / Vainilla, ámbar, almizcle",
    imagen: "Parfums%20de%20Marly%20Layton.avif"
  },
  {
    id: 43,
    activo: true,
    nombre: "Xerjoff Alexandria II",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-dulce",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Palisandro, lavanda, manzana, canela / Rosa, cedro, muguet / Agarwood (oud), sándalo, ámbar, vainilla, almizcle",
    imagen: "Xerjoff%20Alexandria%20II.avif"
  },
  {
    id: 44,
    activo: true,
    nombre: "Amouage Interlude Man",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    notaEspecifica: "cuero-calido",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Bergamota, orégano, pimienta de Jamaica / Ámbar, incienso, cistus, opoponax / Cuero, agarwood ahumado, patchouli, sándalo",
    imagen: "Amouage%20Interlude%20Man.avif"
  },
  {
    id: 45,
    activo: true,
    nombre: "Acqua di Parma Colonia",
    tipo: "Lujo",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    notaEspecifica: "marino-suave",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Suave",
    presupuesto: "Sin límite",
    notas: "Cítricos, bergamota / Lavanda, romero, verbena / Almizcle, madera, vetiver",
    imagen: "Acqua%20di%20Parma%20Colonia.avif"
  },
  {
    id: 46,
    activo: true,
    nombre: "Escentric Molecules Molecule 01",
    tipo: "Lujo",
    aromaPrincipal: "Limpio y Suave",
    subAroma: "Jabón fino",
    notaEspecifica: "jabon-fino",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Suave",
    presupuesto: "Sin límite",
    notas: "Iso E Super — nota única sintética, aroma amaderado-ambarado muy cercano a la piel",
    imagen: "Escentric%20Molecules%20Molecule%2001.avif"
  },
  {
    id: 47,
    activo: true,
    nombre: "Guerlain L'Homme Idéal",
    tipo: "Lujo",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    notaEspecifica: "vainilla-especiada",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Cítricos, naranja amarga, romero, azahar / Almendra, haba tonka / Cuero, cedro, vetiver",
    imagen: "Guerlain%20LHomme%20Ideal.avif"
  },
  {
    id: 48,
    activo: true,
    nombre: "Montblanc Explorer",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "cedro-seco",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Bergamota, pomarosa, salvia / Vetiver, cuero, sándalo / Patchouli, ámbar, madera",
    imagen: "Montblanc%20Explorer.avif"
  },
  {
    id: 49,
    activo: true,
    nombre: "Cartier Pasha de Cartier Parfum",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    notaEspecifica: "ambar-resina",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Sándalo, licor, bálsamo de abeto / Benzoína, haba tonka, ambrocenide / Hoja de patchouli indonesio, labdanum",
    imagen: "Cartier%20Pasha%20de%20Cartier%20Parfum.avif"
  },
  {
    id: 50,
    activo: true,
    nombre: "Diptyque Eau Capitale",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "sandalo-floral",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Suave",
    presupuesto: "Sin límite",
    notas: "Pimienta rosa, bergamota / Rosa, ylang-ylang, canela / Patchouli, musgo, madera",
    imagen: "Diptyque%20Eau%20Capitale.avif"
  }
,
  {
    id: 51,
    activo: true,
    nombre: "Giorgio Armani Code",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    notaEspecifica: "citrico-flor-madera",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Limón, bergamota / Anís estrellado, flor de olivo / Cuero, haba tonka",
    imagen: "Giorgio%20Armani%20Code.avif"
  },
  {
    id: 52,
    activo: true,
    nombre: "Chanel Bleu de Chanel EDT",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico verde / aromático",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Limón, menta, pomelo / Jengibre, nuez moscada / Incienso, cedro, sándalo",
    imagen: "Chanel%20Bleu%20de%20Chanel%20EDT.avif"
  },
  {
    id: 53,
    activo: true,
    nombre: "Prada Luna Rossa Carbon",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    notaEspecifica: "citrico-verde-suave",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Bergamota, pimienta, notas cítricas / Lavanda, geranio / Ambroxan, patchouli",
    imagen: "Prada%20Luna%20Rossa%20Carbon.avif"
  },
  {
    id: 54,
    activo: true,
    nombre: "Versace Dylan Blue",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    notaEspecifica: "marino-intenso",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Toronja, higo de mar / Ambroxan, pimienta / Musgo de encina, pachulí",
    imagen: "Versace%20Dylan%20Blue.avif"
  },
  {
    id: 55,
    activo: true,
    nombre: "Montblanc Legend",
    tipo: "Diseñador",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "cedro-seco",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Bergamota, piña / Lavanda, geranio / Haba tonka, sándalo",
    imagen: "Montblanc%20Legend.avif"
  },
  {
    id: 56,
    activo: true,
    nombre: "Azzaro The Most Wanted",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    notaEspecifica: "ambar-resina",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Cardamomo / Toffee / Madera ambarada",
    imagen: "Azzaro%20The%20Most%20Wanted.avif"
  },
  {
    id: 57,
    activo: true,
    nombre: "Yves Saint Laurent La Nuit de l'Homme",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    notaEspecifica: "especiado-fresco",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Cardamomo, bergamota / Lavanda, cedro / Haba tonka, vetiver",
    imagen: "Yves%20Saint%20Laurent%20La%20Nuit%20de%20l%27Homme.avif"
  },
  {
    id: 58,
    activo: true,
    nombre: "Dolce & Gabbana Light Blue",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    notaEspecifica: "citrico-simple",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Suave",
    presupuesto: "Medio",
    notas: "Manzana, limón siciliano / Jazmín, junco / Cedro, almizcle",
    imagen: "Dolce%20%26%20Gabbana%20Light%20Blue.avif"
  },
  {
    id: 59,
    activo: true,
    nombre: "Burberry Hero",
    tipo: "Diseñador",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "cedro-seco",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Bergamota / Enebro, pimienta negra / Cedro Atlas, cedro Virginia, cedro Himalaya",
    imagen: "Burberry%20Hero.avif"
  },
  {
    id: 60,
    activo: true,
    nombre: "Guerlain Habit Rouge",
    tipo: "Diseñador",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    notaEspecifica: "cuero-calido",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Limón, palo de rosa brasileño, naranja, bergamota / Rosa, clavel, sándalo, canela, pachulí, jazmín, cedro / Vainilla, cuero, benjuí, ámbar, musgo de encina",
    imagen: "Guerlain%20Habit%20Rouge.avif"
  },
  {
    id: 61,
    activo: true,
    nombre: "Tom Ford Noir Extreme",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    notaEspecifica: "especiado-intenso",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Cardamomo, nuez moscada / Rosa, jengibre / Ámbar, vainilla, cacao",
    imagen: "Tom%20Ford%20Noir%20Extreme.avif"
  },
  {
    id: 62,
    activo: true,
    nombre: "Paco Rabanne 1 Million",
    tipo: "Diseñador",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    notaEspecifica: "cuero-fresco",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Toronja, menta / Canela, especias / Cuero, ámbar, madera blanca",
    imagen: "Paco%20Rabanne%201%20Million.avif"
  },
  {
    id: 63,
    activo: true,
    nombre: "Jean Paul Gaultier Le Male",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "canela-clasica",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Menta, lavanda / Canela, comino / Vainilla, sándalo, ámbar",
    imagen: "Le%20Male%20Jean%20Paul%20Gaultier%20for%20men.avif"
  },
  {
    id: 64,
    activo: true,
    nombre: "Dior Homme Intense",
    tipo: "Diseñador",
    aromaPrincipal: "Limpio y Suave",
    subAroma: "Iris elegante",
    notaEspecifica: "iris-elegante",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Lavanda, iris / Cacao, ámbar / Cedro, vetiver",
    imagen: "Dior%20Homme%20Intense.avif"
  },
  {
    id: 65,
    activo: true,
    nombre: "Versace Eros Flame",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "ambar-resina",
    momento: "Fiesta",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Pimienta negra, mandarina / Especias, canela / Haba tonka, madera de Bengala",
    imagen: "Versace%20Eros%20Flame.avif"
  },
  {
    id: 66,
    activo: true,
    nombre: "Lattafa Khamrah Qahwa",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "cafe-datiles",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Café, canela / Dátiles, especias / Ámbar, vainilla, oud",
    imagen: "Lattafa%20Khamrah%20Qahwa.avif"
  },
  {
    id: 67,
    activo: true,
    nombre: "Lattafa Khamrah Dukhan",
    tipo: "Árabe",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Tabaco dulce",
    notaEspecifica: "tabaco-miel",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Especias, pimento, mandarina / Incienso, labdanum, azahar, patchouli / Praliné, tabaco, ámbar, haba tonka, benzoína",
    imagen: "Lattafa%20Khamrah%20Dukhan.avif"
  },
  {
    id: 68,
    activo: true,
    nombre: "Lattafa Asad Bourbon",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "cafe-datiles",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Ron bourbon, piña / Canela, especias / Ámbar, madera, vainilla",
    imagen: "Lattafa%20Asad%20Bourbon.avif"
  },
  {
    id: 69,
    activo: true,
    nombre: "Afnan Supremacy Collector's Edition",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "cedro-citrico",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Piña, bergamota / Abedul, especias / Ámbar, almizcle, oud",
    imagen: "Afnan%20Supremacy%20Collector%27s%20Edition.avif"
  },
  {
    id: 70,
    activo: true,
    nombre: "Armaf Odyssey Mandarin Sky",
    tipo: "Árabe",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    notaEspecifica: "citrico-flor-madera",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Mandarina, bergamota / Jazmín, especias / Almizcle, madera clara",
    imagen: "Armaf%20Odyssey%20Mandarin%20Sky.avif"
  },
  {
    id: 71,
    activo: true,
    nombre: "Lattafa Opulent Dubai",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-tropical",
    momento: "Fiesta",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Mango, toronja, limón, jengibre / Jazmín, cedro, violeta / Ámbar gris, madera, musgo, benzoína",
    imagen: "Lattafa%20Opulent%20Dubai.avif"
  },
  {
    id: 73,
    activo: true,
    nombre: "Tom Ford Ombré Leather Parfum",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    notaEspecifica: "cuero-calido",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Cardamomo, azafrán / Cuero, jazmín / Ámbar, cuero, almizcle",
    imagen: "Tom%20Ford%20Ombr%C3%A9%20Leather%20Parfum.avif"
  },
  {
    id: 74,
    activo: true,
    nombre: "Creed Aventus Cologne",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "cedro-citrico",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Mandarina, jengibre, pimienta rosa, bergamota / Vetiver, patchouli, sándalo, piña / Almizcle, haba tonka, styrax, abedul",
    imagen: "Creed%20Aventus%20Cologne.avif"
  },
  {
    id: 75,
    activo: true,
    nombre: "Parfums de Marly Herod",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "canela-clasica",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Canela, pimienta / Osmanthus, hoja de tabaco, labdanum, incienso / Vainilla, cedro, vetiver, patchouli, almizcle",
    imagen: "Parfums%20de%20Marly%20Herod.avif"
  },
  {
    id: 76,
    activo: true,
    nombre: "Xerjoff Erba Pura",
    tipo: "Lujo",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-citrico",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Naranja siciliana, bergamota de Calabria, limón siciliano / Frutas mediterráneas / Almizcle blanco, vainilla de Madagascar, ámbar",
    imagen: "Erba%20Pura%20Xerjoff.avif"
  },
  {
    id: 77,
    activo: true,
    nombre: "Amouage Reflection Man",
    tipo: "Lujo",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    notaEspecifica: "citrico-verde-suave",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Romero, pimienta rosa, petitgrain / Jazmín, neroli, iris, ylang-ylang / Sándalo, cedro, vetiver, patchouli",
    imagen: "Amouage%20Reflection%20Man.avif"
  },
  {
    id: 78,
    activo: true,
    nombre: "Initio Oud for Greatness",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-resinoso",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Azafrán, nuez moscada, lavanda / Agarwood (oud) / Patchouli, almizcle",
    imagen: "Oud%20for%20Greatness%20Initio%20Parfums%20Prives%20for%20women%20and%20men.avif"
  },
  {
    id: 79,
    activo: true,
    nombre: "Nishane Hacivat",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "cedro-citrico",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Piña, bergamota, toronja / Jazmín, oakmoss / Patchouli",
    imagen: "Nishane%20Hacivat.avif"
  },
  {
    id: 80,
    activo: true,
    nombre: "Byredo Bal d'Afrique",
    tipo: "Lujo",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    notaEspecifica: "marino-suave",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Suave",
    presupuesto: "Sin límite",
    notas: "Bergamota, limón, neroli, caléndula africana, bucchu / Violeta, jazmín, ciclamen / Ámbar negro, almizcle, vetiver, cedro marroquí",
    imagen: "Byredo%20Bal%20d%27Afrique.avif"
  },
  {
    id: 81,
    activo: true,
    nombre: "Rasasi Hawas Elixir",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "especiado-intenso",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Menta, bergamota, artemisa / Chocolate oscuro, lavanda, benzoína / Vainilla, haba tonka, almizcle blanco",
    imagen: "Rasasi%20Hawas%20Elixir.avif"
  },
  {
    id: 82,
    activo: true,
    nombre: "Al Haramain L'Aventure Fraiche",
    tipo: "Árabe",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    notaEspecifica: "citrico-verde-suave",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Limón, jengibre / Té, cardamomo / Almizcle, sándalo, madera",
    imagen: "Al%20Haramain%20L%27Aventure%20Fraiche.avif"
  },
  {
    id: 83,
    activo: true,
    nombre: "Lattafa Yara Tous",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-citrico",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Fruta de la pasión, pera / Orquídea, flores blancas / Almizcle, vainilla, praliné",
    imagen: "Yara%20Tous%20Lattafa%20Perfumes%20for%20women.avif"
  },
  {
    id: 84,
    activo: true,
    nombre: "Armaf Club de Nuit Sillage",
    tipo: "Árabe",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    notaEspecifica: "citrico-amaderado-potente",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Bergamota, limón, lima, grosella negra, hoja de violeta, jengibre / Rosa, iris, jazmín / Ambroxan, almizcle, sándalo, cedro",
    imagen: "Armaf%20Club%20de%20Nuit%20Sillage.avif"
  },
  {
    id: 85,
    activo: true,
    nombre: "Swiss Arabian Shaghaf Oud Elixir",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-dulce",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Oud, azafrán, pimienta rosa / Praliné, rosa, salvia / Vainilla, ámbar, almizcle",
    imagen: "Shaghaf%20Oud%20Elixir%20Swiss%20Arabian%20for%20women%20and%20men.avif"
  },
  {
    id: 86,
    activo: true,
    nombre: "Lattafa Fakhar Black",
    tipo: "Árabe",
    aromaPrincipal: "Limpio y Suave",
    subAroma: "Jabón fino",
    notaEspecifica: "jabon-fino",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Manzana, bergamota, jengibre / Lavanda, salvia / Haba tonka, cedro, vetiver",
    imagen: "Lattafa%20Fakhar%20Black.avif"
  },
  {
    id: 87,
    activo: true,
    nombre: "Al Haramain Amber Oud Tobacco Edition",
    tipo: "Árabe",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Tabaco dulce",
    notaEspecifica: "tabaco-cacao",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Tabaco, especias dulces / Oud, cacao / Vainilla, ámbar, madera",
    imagen: "Al%20Haramain%20Amber%20Oud%20Tobacco%20Edition.avif"
  },
  {
    id: 88,
    activo: true,
    nombre: "Lattafa The Kingdom",
    tipo: "Árabe",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Tabaco dulce",
    notaEspecifica: "tabaco-miel",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Lavanda, menta, salvia / Vainilla, tabaco, azahar / Haba tonka, benjuí, labdanum",
    imagen: "Lattafa%20The%20Kingdom.avif"
  },
  {
    id: 89,
    activo: true,
    nombre: "Afnan 9PM Femme",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "floral-dulce",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Frambuesa, violeta, manzana, naranja / Rosa, peonía, iris, jazmín / Ciprés, pino, ámbar, cedro",
    imagen: "Afnan%209PM%20Femme.avif"
  },
  {
    id: 90,
    activo: true,
    nombre: "Nautica Voyage",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Hojas verdes, manzana / Loto, mimosa / Almizcle, cedro, musgo de encina, ámbar",
    imagen: "Nautica%20Voyage.avif"
  },
  {
    id: 91,
    activo: true,
    nombre: "Kilian Angel's Share",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "canela-clasica",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Coñac, canela / Roble, nuez moscada / Haba tonka, sándalo",
    imagen: "Kilian%20Angel%27s%20Share.avif"
  },
  {
    id: 92,
    activo: true,
    nombre: "Roja Parfums Elysium",
    tipo: "Lujo",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    notaEspecifica: "aromatico-herbal",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Bergamota, limón / Salvia, geranio / Almizcle, vetiver, ámbar",
    imagen: "Roja%20Parfums%20Elysium.avif"
  },
  {
    id: 93,
    activo: true,
    nombre: "Mancera Cedrat Boise",
    tipo: "Lujo",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    notaEspecifica: "citrico-simple",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Cedrat, bergamota / Cedro, jazmín / Almizcle, ámbar",
    imagen: "Mancera%20Cedrat%20Boise.avif"
  },
  {
    id: 94,
    activo: true,
    nombre: "Montale Intense Café",
    tipo: "Lujo",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    notaEspecifica: "vainilla-pura",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Café, canela / Chocolate, cacao / Vainilla, ámbar, madera",
    imagen: "Montale%20Intense%20Caf%C3%A9.avif"
  },
  {
    id: 95,
    activo: true,
    nombre: "Xerjoff Naxos",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Tabaco dulce",
    notaEspecifica: "tabaco-miel",
    momento: "Citas",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Bergamota, lavanda / Miel, tabaco / Haba tonka, vainilla, sándalo",
    imagen: "Xerjoff%20Naxos.avif"
  },
  {
    id: 96,
    activo: true,
    nombre: "Amouage Interlude Woman",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-resinoso",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Incienso, bergamota / Jazmín, clavo / Pachulí, oud, ámbar",
    imagen: "Amouage%20Interlude%20Woman.avif"
  },
  {
    id: 97,
    activo: true,
    nombre: "Parfums de Marly Percival",
    tipo: "Lujo",
    aromaPrincipal: "Limpio y Suave",
    subAroma: "Jabón fino",
    notaEspecifica: "jabon-fino",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Manzana, bergamota / Lavanda, geranio / Almizcle, sándalo, vainilla",
    imagen: "Parfums%20de%20Marly%20Percival.avif"
  },
  {
    id: 99,
    activo: true,
    nombre: "Bvlgari Man in Black",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    notaEspecifica: "cuero-calido",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Especias, ron / Cuero, tabaco / Haba tonka, ámbar, cuero",
    imagen: "Bvlgari%20Man%20in%20Black.avif"
  },
  {
    id: 100,
    activo: true,
    nombre: "Maison Francis Kurkdjian Grand Soir",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    notaEspecifica: "ambar-resina",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Ámbar, vainilla / Haba tonka, benzoína / Ládano, almizcle, madera",
    imagen: "Maison%20Francis%20Kurkdjian%20Grand%20Soir.avif"
  }
,
  {
    id: 101,
    activo: true,
    nombre: "Afnan 9PM Night Out",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "especiado-intenso",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Joven",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Fruta de dragón, bergamota, coñac, lavanda, manzana / Cardamomo, ante, toffee, cedro / Haba tonka, akigalawood, patchouli",
    imagen: "Afnan%209PM%20Night%20Out.avif"
  }
,
  {
    id: 102,
    activo: true,
    nombre: "Paco Rabanne 1 Million Lucky",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-citrico",
    momento: "Citas",
    clima: "Templado",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Toronja, mandarina / Avellana, almendra / Haba tonka, madera blanca",
    imagen: "Paco%20Rabanne%201%20Million%20Lucky.avif"
  }
,
  {
    id: 103,
    activo: true,
    nombre: "Jean Paul Gaultier Le Male Le Parfum",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    notaEspecifica: "vainilla-especiada",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Lavanda, vainilla / Especias, cacao / Haba tonka, ámbar, madera",
    imagen: "Le%20Male%20Le%20Parfum%20Jean%20Paul%20Gaultier%20for%20men.avif"
  },
  {
    id: 104,
    activo: true,
    nombre: "Jean Paul Gaultier Le Male Elixir Absolu",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    notaEspecifica: "vainilla-especiada",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Lavanda, menta / Vainilla intensa, benzoína / Miel, tabaco, haba tonka concentrada",
    imagen: "Jean%20Paul%20Gaultier%20Le%20Male%20Elixir%20Absolu.avif"
  },
  {
    id: 105,
    activo: true,
    nombre: "Jean Paul Gaultier Le Beau Paradise Garden",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-citrico",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Joven",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Notas verdes, notas acuáticas, menta, jengibre / Coco, higo, sal / Haba tonka, sándalo",
    imagen: "Jean%20Paul%20Gaultier%20Le%20Male%20Paradise%20Garden.avif"
  },
  {
    id: 106,
    activo: true,
    nombre: "Jean Paul Gaultier Le Beau Le Parfum",
    tipo: "Diseñador",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "sandalo-limpio",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Bergamota / Madera de coco / Cedro, vainilla, haba tonka",
    imagen: "Jean%20Paul%20Gaultier%20Le%20Beau%20Le%20Parfum.avif"
  }
,
  {
    id: 107,
    activo: true,
    nombre: "Xerjoff Torino 21",
    tipo: "Lujo",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    notaEspecifica: "menta-dominante",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Menta, limón, albahaca, tomillo / Grosella negra, lavanda, romero, jazmín / Almizcle, verbena",
    imagen: "Torino%2021.avif"
  },
  {
    id: 108,
    activo: true,
    nombre: "Armaf Club de Nuit Urban Man Elixir",
    tipo: "Árabe",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    notaEspecifica: "citrico-amaderado-potente",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Bergamota, pimienta rosa / Lavanda, azafrán / Ambroxan, ámbar, cedro",
    imagen: "Armaf%20Club%20de%20Nuit%20Urban%20Man%20Elixir.avif"
  }
,
  {
    id: 111,
    activo: true,
    nombre: "French Avenue Vulcan Feu",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-tropical",
    momento: "Fiesta",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Mango, jengibre, limón, frutos rojos / Cumarina, jazmín, cedro, pimienta rosa, violeta, praliné / Almizcle, ámbar, oud, cypriol, haba tonka",
    imagen: "French%20Avenue%20Vulcan%20Feu.avif"
  },
  {
    id: 112,
    activo: true,
    nombre: "Emporio Armani Stronger With You Intensely",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "especiado-intenso",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Pimienta rosa, enebro, violeta / Lavanda, salvia, toffee, canela / Cuero, ámbar, vainilla, haba tonka",
    imagen: "Emporio%20Armani%20Stronger%20With%20You%20Intensely.avif"
  }
,
  {
    id: 113,
    activo: true,
    nombre: "French Avenue Liquid Brun",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "canela-clasica",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Canela, flor de naranjo, cardamomo, bergamota / Vainilla bourbon, elemi / Almizcle, praliné, ambroxan, guaiac wood",
    imagen: "French%20Avenue%20Liquid%20Brun.avif"
  }
,
  {
    id: 114,
    activo: true,
    nombre: "Tom Ford Fucking Fabulous",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    notaEspecifica: "cuero-calido",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Salvia esclarea, lavanda, almendra amarga / Cuero, iris, vainilla / Haba tonka, cashmeran, ámbar",
    imagen: "Tom%20Ford%20Fucking%20Fabulous.avif"
  }
,
  {
    id: 115,
    activo: true,
    nombre: "Xerjoff Erba Gold",
    tipo: "Lujo",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico puro",
    notaEspecifica: "citrico-flor-madera",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Bergamota, limón, naranja / Miel, azahar, jazmín / Almizcle, vainilla, ámbar, cedro",
    imagen: "Xerjoff%20Erba%20Gold.avif"
  }
,
  {
    id: 116,
    activo: true,
    nombre: "Xerjoff Accento",
    tipo: "Lujo",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "vainilla-pura",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Piña, jacinto / Iris, pimienta rosa, jazmín / Almizcle, ámbar, vetiver, vainilla, patchouli",
    imagen: "Xerjoff%20Accento.avif"
  }
,
  {
    id: 117,
    activo: true,
    nombre: "Creed Aventus Absolu",
    tipo: "Lujo",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    notaEspecifica: "especiado-fresco",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Bergamota de Calabria, jengibre, toronja, piña / Cardamomo, canela / Patchouli, vetiver haitiano, labdanum",
    imagen: "Creed%20Aventus%20Absolu.avif"
  }
,
  {
    id: 118,
    activo: true,
    nombre: "Giorgio Armani Stronger With You Powerfully",
    tipo: "Diseñador",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    notaEspecifica: "vainilla-especiada",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Cereza, mandarina / Especias, lavanda / Castaña, vainilla, madera ambarada",
    imagen: "Giorgio%20Armani%20Stronger%20With%20You%20Powerfully.avif"
  }
,
  {
    id: 119,
    activo: true,
    nombre: "Giorgio Armani Acqua di Giò Profondo Parfum",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    notaEspecifica: "marino-suave",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Notas marinas, mandarina verde / Mimosa, lavanda, ciprés / Patchouli, labdanum, notas minerales",
    imagen: "Giorgio%20Armani%20Acqua%20di%20Gi%C3%B2%20Profondo%20Parfum.avif"
  }
,
  {
    id: 121,
    activo: true,
    nombre: "Lattafa Bade'e Al Oud Amethyst",
    tipo: "Árabe",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-dulce",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Pimienta rosa, bergamota / Rosa turca, rosa búlgara, jazmín / Agarwood (oud), ámbar, vainilla",
    imagen: "Lattafa%20Badee%20Al%20Oud%20Amethyst.avif"
  }
,
  {
    id: 122,
    activo: true,
    nombre: "Lattafa Bade'e Al Oud Honor & Glory",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-tropical",
    momento: "Fiesta",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Piña, crème brûlée / Canela, cúrcuma, pimienta negra, benzoína / Vainilla, sándalo, cashmeran, musgo",
    imagen: "Lattafa%20Bade%27e%20Al%20Oud%20Honor%20%26%20Glory.avif"
  }
,
  {
    id: 123,
    activo: true,
    nombre: "Armaf Club De Nuit Lionheart Man",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "especiado-intenso",
    momento: "Fiesta",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Lavanda, menta / Benzoína, vainilla / Miel, haba tonka, tabaco",
    imagen: "Armaf%20Club%20De%20Nuit%20Lionheart%20Man.avif"
  }
,
  {
    id: 124,
    activo: true,
    nombre: "Armaf Club de Nuit Blue Iconic",
    tipo: "Árabe",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico verde / aromático",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Toronja, menta, limón, pimienta rosa / Jengibre, melón, jazmín, nuez moscada / Incienso, ámbar, cedro, sándalo, patchouli",
    imagen: "Armaf%20Club%20de%20Nuit%20Blue%20Iconic.avif"
  }
,
  {
    id: 125,
    activo: true,
    nombre: "Armaf Club de Nuit Untold",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    notaEspecifica: "ambar-resina",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Azafrán, jazmín / Ámbar gris, madera ambarada / Resina de abeto, cedro",
    imagen: "Armaf%20Club%20de%20Nuit%20Untold.avif"
  }
,
  {
    id: 126,
    activo: true,
    nombre: "Armaf Club de Nuit Precieux I",
    tipo: "Árabe",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Frutal jugoso",
    notaEspecifica: "frutal-tropical",
    momento: "Fiesta",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Económico",
    notas: "Piña, limón, bergamota, caramelo, pimienta rosa / Musgo de encina, madera blanca, jazmín, anís / Ambroxan, almizcle blanco, cedro, patchouli, ámbar, cuero, vainilla",
    imagen: "Armaf%20Club%20de%20Nuit%20Precieux%20I.avif"
  }
,
  {
    id: 127,
    activo: true,
    nombre: "Rasasi Hawas Fire",
    tipo: "Árabe",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    notaEspecifica: "marino-intenso",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Salvia esclarea / Jazmín egipcio, notas marinas / Ámbar, ámbar gris, notas minerales",
    imagen: "Rasasi%20Hawas%20Fire.avif"
  }
,
  {
    id: 128,
    activo: true,
    nombre: "Tom Ford Tuscan Leather",
    tipo: "Lujo",
    aromaPrincipal: "Cuero / Tabaco",
    subAroma: "Cuero elegante",
    notaEspecifica: "cuero-fresco",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Frambuesa, azafrán, tomillo / Olíbano, jazmín / Cuero, gamuza, madera, ámbar",
    imagen: "Tom%20Ford%20Tuscan%20Leather.avif"
  }
,
  {
    id: 129,
    activo: true,
    nombre: "Tom Ford Grey Vetiver Parfum",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "cedro-seco",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Azahar de naranjo / Azafrán / Vetiver haitiano",
    imagen: "Tom%20Ford%20Grey%20Vetiver%20Parfum.avif"
  }
,
  {
    id: 130,
    activo: true,
    nombre: "Tom Ford Neroli Portofino",
    tipo: "Lujo",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico verde / aromático",
    momento: "Diario",
    clima: "Caliente / Sol",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Bergamota, limón, mandarina, lavanda, romero / Neroli, azahar, jazmín, pittosporum / Ámbar, angélica, ambreta",
    imagen: "Tom%20Ford%20Neroli%20Portofino.avif"
  }
,
  {
    id: 131,
    activo: true,
    nombre: "Tom Ford Black Orchid Parfum",
    tipo: "Lujo",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    notaEspecifica: "vainilla-pura",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Trufa, ciruela / Ron, ylang-ylang, orquídea negra / Patchouli",
    imagen: "Tom%20Ford%20Black%20Orchid%20Parfum.avif"
  }
,
  {
    id: 132,
    activo: true,
    nombre: "Chanel Égoïste",
    tipo: "Diseñador",
    aromaPrincipal: "Madera",
    subAroma: "Madera suave / Cedro",
    notaEspecifica: "sandalo-floral",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Palo de rosa, cilantro, mandarina siciliana / Canela, rosa de Damasco, clavel / Sándalo, tabaco, vainilla, cuero, ámbar",
    imagen: "Egoiste%20Chanel.avif"
  }
,
  {
    id: 133,
    activo: true,
    nombre: "Chanel Allure Homme Sport Eau Extrême",
    tipo: "Diseñador",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    notaEspecifica: "aromatico-herbal",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Medio",
    notas: "Mandarina siciliana, menta, ciprés, salvia esclarea / Pimienta / Haba tonka, almizcle, aldehídos",
    imagen: "Chanel%20Allure%20Homme%20Sport%20Eau%20Extr%C3%AAme.avif"
  }
,
  {
    id: 134,
    activo: true,
    nombre: "Creed Green Irish Tweed",
    tipo: "Lujo",
    aromaPrincipal: "Fresco",
    subAroma: "Menta / Té / Verde",
    notaEspecifica: "aromatico-herbal",
    momento: "Diario",
    clima: "Templado",
    estilo: "Formal",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Bergamota, limón, menta, verbena / Geranio, lavanda, violeta / Sándalo, cedro, musgo de encina, ambroxan",
    imagen: "Creed%20Green%20Irish%20Tweed.avif"
  }
,
  {
    id: 135,
    activo: true,
    nombre: "Creed Silver Mountain Water",
    tipo: "Lujo",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico verde / aromático",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Bergamota, grosella negra, galbanum, naranja / Té verde, acorde ozónico / Sándalo, almizcle",
    imagen: "Creed%20Silver%20Mountain%20Water.avif"
  }
,
  {
    id: 136,
    activo: true,
    nombre: "Yves Saint Laurent Y Le Parfum",
    tipo: "Diseñador",
    aromaPrincipal: "Cítrico",
    subAroma: "Cítrico verde / aromático",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Toronja, manzana, jengibre, aldehídos / Salvia, lavanda, geranio / Haba tonka, cedro, olíbano, patchouli",
    imagen: "Yves%20Saint%20Laurent%20Y%20Le%20Parfum.avif"
  }
,
  {
    id: 137,
    activo: true,
    nombre: "Yves Saint Laurent MYSLF L'Absolu",
    tipo: "Diseñador",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Ámbar / Pimienta",
    notaEspecifica: "especiado-fresco",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Modo Bestia",
    presupuesto: "Medio",
    notas: "Jengibre, bergamota, cardamomo / Azahar de naranjo / Patchouli",
    imagen: "Yves%20Saint%20Laurent%20MYSLF%20L%27Absolu.avif"
  }
,
  {
    id: 139,
    activo: true,
    nombre: "Maison Francis Kurkdjian Oud Satin Mood",
    tipo: "Lujo",
    aromaPrincipal: "Madera",
    subAroma: "Oud exótico",
    notaEspecifica: "fuerte-dulce",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Formal",
    potencia: "Modo Bestia",
    presupuesto: "Sin límite",
    notas: "Rosa búlgara, violeta, fresa / Rosa turca / Agarwood (oud), vainilla, ámbar, benzoína, caramelo, cedro",
    imagen: "Maison%20Francis%20Kurkdjian%20Oud%20Satin%20Mood.avif"
  }
,
  {
    id: 140,
    activo: true,
    nombre: "Parfums de Marly Pegasus",
    tipo: "Lujo",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    notaEspecifica: "vainilla-especiada",
    momento: "Citas",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Bergamota, heliotropo, comino / Jazmín, almendra amarga, lavanda / Ámbar, vainilla, sándalo",
    imagen: "Parfums%20de%20Marly%20Pegasus.avif"
  }
,
  {
    id: 141,
    activo: true,
    nombre: "Parfums de Marly Althaïr",
    tipo: "Lujo",
    aromaPrincipal: "Dulce / Gourmand",
    subAroma: "Vainilla / Caramelo",
    notaEspecifica: "vainilla-especiada",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Sin límite",
    notas: "Canela, azahar, cardamomo, bergamota / Vainilla bourbon, elemi / Praliné, almizcle, ambroxan, haba tonka, guaiac wood",
    imagen: "Parfums%20de%20Marly%20Althair.avif"
  }
,
  {
    id: 142,
    activo: true,
    nombre: "Al Haramain Détour Noir",
    tipo: "Árabe",
    aromaPrincipal: "Cálido / Especiado",
    subAroma: "Miel / Canela",
    notaEspecifica: "canela-clasica",
    momento: "Citas",
    clima: "Frío / Noche",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Manzana, lavanda, jazmín, violeta / Vainilla, patchouli, bergamota, mandarina / Sándalo, cardamomo, pimienta, guaiac wood",
    imagen: "Al%20Haramain%20D%C3%A9tour%20Noir.avif"
  }
,
  {
    id: 143,
    activo: true,
    nombre: "Al Haramain Amber Oud Carbon Edition",
    tipo: "Árabe",
    aromaPrincipal: "Fresco",
    subAroma: "Marina / Salada",
    notaEspecifica: "marino-intenso",
    momento: "Diario",
    clima: "Templado",
    estilo: "Versátil",
    potencia: "Normal",
    presupuesto: "Económico",
    notas: "Bergamota, lavanda, romero / Notas marinas, geranio, salvia / Musgo, vetiver, ámbar, cedro",
    imagen: "Al%20Haramain%20Amber%20Oud%20Carbon%20Edition.avif"
  }
];

// Fallback SVG (data URI) — se usa si la imagen real no carga
const FALLBACK_IMG =
  "data:image/svg+xml;utf8," +
  encodeURIComponent(`
  <svg xmlns='http://www.w3.org/2000/svg' width='375' height='500' viewBox='0 0 375 500'>
    <defs>
      <linearGradient id='g' x1='0' y1='0' x2='0' y2='1'>
        <stop offset='0%' stop-color='#1a1a1a'/>
        <stop offset='100%' stop-color='#2b2410'/>
      </linearGradient>
    </defs>
    <rect width='375' height='500' fill='url(#g)'/>
    <g fill='none' stroke='#ffb703' stroke-width='2' opacity='0.85'>
      <rect x='140' y='150' width='95' height='170' rx='10'/>
      <rect x='160' y='110' width='55' height='45' rx='6'/>
      <line x1='140' y1='210' x2='235' y2='210'/>
      <line x1='140' y1='250' x2='235' y2='250'/>
    </g>
    <text x='187' y='370' font-family='Georgia, serif' font-size='16' fill='#ffb703' text-anchor='middle'>Perfume</text>
    <text x='187' y='392' font-family='Georgia, serif' font-size='12' fill='#c9c9c9' text-anchor='middle'>Imagen no disponible</text>
  </svg>`);
